##Crear rquta
post http://localhost:3000/usuario/users
Content-Type: application/json

{
    "nombre_completo": "Javier nombre2",
    "apellidos":" Apellido1 Apellido 2",
    "correo": "Javier1@insightflow.cl",
    "usuario": "UsuarioJavier1",
    "contrasenia": "passJavier",
    "fecha_nacimiento": "2004-11-25",
    "telefono":"+56 9 3333 2222",
    "direccion": "Direccion6"
    
} 

### Login usuario
post http://localhost:3000/Usuario/login
Content-Type: application/json

{
    "usuario":"UsuarioJavier1",
    "contrasenia":"passJavier"
}

### Get all usuarios
get http://localhost:3000/usuario/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YWJjYjE1Yy0zYjU1LTQ1ZjMtYTNjMC1jZTVhMDI3NjNjZjEiLCJ1c2VybmFtZSI6IlVzdWFyaW9KYXZpZXIiLCJqdGkiOiJiOTI1MDhhYy1lYzQzLTRlNjMtYjNlOC1jZTJiODQ1YTA2NjciLCJpYXQiOjE3NjQ3NzU2MjksImV4cCI6MTc2NDc3OTIyOX0.gtSukgrke66fFaKx3RoGYRpc4lUB80dZ1MJk0herCOg

#### Get Usuario por id
get http://localhost:3000/usuario/users/173b9389-437c-44ff-a8da-d3ad8f38eff7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YWJjYjE1Yy0zYjU1LTQ1ZjMtYTNjMC1jZTVhMDI3NjNjZjEiLCJ1c2VybmFtZSI6IlVzdWFyaW9KYXZpZXIiLCJqdGkiOiJiOTI1MDhhYy1lYzQzLTRlNjMtYjNlOC1jZTJiODQ1YTA2NjciLCJpYXQiOjE3NjQ3NzU2MjksImV4cCI6MTc2NDc3OTIyOX0.gtSukgrke66fFaKx3RoGYRpc4lUB80dZ1MJk0herCOg

### Actualizar campos

patch http://localhost:3000/usuario/users/173b9389-437c-44ff-a8da-d3ad8f38eff7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YWJjYjE1Yy0zYjU1LTQ1ZjMtYTNjMC1jZTVhMDI3NjNjZjEiLCJ1c2VybmFtZSI6IlVzdWFyaW9KYXZpZXIiLCJqdGkiOiJiOTI1MDhhYy1lYzQzLTRlNjMtYjNlOC1jZTJiODQ1YTA2NjciLCJpYXQiOjE3NjQ3NzU2MjksImV4cCI6MTc2NDc3OTIyOX0.gtSukgrke66fFaKx3RoGYRpc4lUB80dZ1MJk0herCOg
Content-Type: application/json

{
    "nombre_completo": "Javier nombre2 apellido 1 apellido 2",
    "correo": "Javier@insightflow.cl",
    "usuario": "UsuarioJavier1",
    "contrasenia": "passJavier",
    "fecha_nacimiento": "2004-11-25",
    "telefono":"+56 9 3333 2222",
    "direccion": "Direccion6"
}

### sofdelete
delete http://localhost:3000/usuario/users/173b9389-437c-44ff-a8da-d3ad8f38eff7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YWJjYjE1Yy0zYjU1LTQ1ZjMtYTNjMC1jZTVhMDI3NjNjZjEiLCJ1c2VybmFtZSI6IlVzdWFyaW9KYXZpZXIiLCJqdGkiOiJiOTI1MDhhYy1lYzQzLTRlNjMtYjNlOC1jZTJiODQ1YTA2NjciLCJpYXQiOjE3NjQ3NzU2MjksImV4cCI6MTc2NDc3OTIyOX0.gtSukgrke66fFaKx3RoGYRpc4lUB80dZ1MJk0herCOg


###
post https://insightflow-api-tj4n.onrender.com/usuario/users
Content-Type: application/json

{
    "nombre_completo": "Javier nombre2",
    "apellidos":" Apellido1 Apellido 2",
    "correo": "Javier@insightflow.cl",
    "usuario": "UsuarioJavier",
    "contrasenia": "passJavier",
    "fecha_nacimiento": "2004-11-25",
    "telefono":"+56 9 3333 2222",
    "direccion": "Direccion6"
    
} 
###

post https://insightflow-api-tj4n.onrender.com/usuario/login
Content-Type: application/json

{
    "usuario":"UsuarioJavier",
    "contrasenia":"passJavier"
}
###
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYjNjN2RiNi1lYmJhLTQxOTAtYmMxYS1jNjk0ZmJjZjljNjIiLCJ1c2VybmFtZSI6IlVzdWFyaW9KYXZpZXIiLCJqdGkiOiJjNDNlZmYyYy01NjRjLTRiNWMtYmVjZS1hOTk3N2E3ZWI3MmMiLCJpYXQiOjE3NjQ4MDY1ODYsImV4cCI6MTc2NDgxMDE4Nn0.zLW2p5KX_JFV022WJ4iLNPNhy7JDRiAMUmr-RCLkupE
###
get https://insightflow-api-tj4n.onrender.com/usuario/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYjNjN2RiNi1lYmJhLTQxOTAtYmMxYS1jNjk0ZmJjZjljNjIiLCJ1c2VybmFtZSI6IlVzdWFyaW9KYXZpZXIiLCJqdGkiOiJjNDNlZmYyYy01NjRjLTRiNWMtYmVjZS1hOTk3N2E3ZWI3MmMiLCJpYXQiOjE3NjQ4MDY1ODYsImV4cCI6MTc2NDgxMDE4Nn0.zLW2p5KX_JFV022WJ4iLNPNhy7JDRiAMUmr-RCLkupE

### verificartoken
GET http://localhost:3000/usuario/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkM2YxYzliNi01YTg2LTQ3ZmItYTIxOS0wZGQ3MGM4NDgwYTUiLCJ1c2VybmFtZSI6IlVzdWFyaW9KYXZpZXIxIiwianRpIjoiMDU4NThmMjAtMmQ2OS00MmU2LTljZTktNWM1MTMwZDBmMTA3IiwiaWF0IjoxNzY0ODExNzYxLCJleHAiOjE3NjQ4MTUzNjF9.I8s4hquXenW9Lkn72EGg6V3Ps2C0PSROGBaU4xPdNSg


###
post https://user-services-13hx.onrender.com/usuario/users
Content-Type: application/json

{
    "nombre_completo": "Javier nombre2",
    "apellidos":" Apellido1 Apellido 2",
    "correo": "Javier1@insightflow.cl",
    "usuario": "u1",
    "contrasenia": "pass1",
    "fecha_nacimiento": "2004-11-25",
    "telefono":"+56 9 3333 2222",
    "direccion": "Direccion6"  
} 
###
post https://user-services-13hx.onrender.com/Usuario/login
Content-Type: application/json

{
    "usuario":"u1",
    "contrasenia":"pass1"
}
###
get https://user-services-13hx.onrender.com/usuario/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYTYzMmMxNS1jY2QyLTRiZWEtYTAzYS1kNDM3NTBiYTZiODYiLCJ1c2VybmFtZSI6InUxIiwianRpIjoiODFiNzE5MTUtYjU3ZC00ZjM0LWI0MzgtYjU0Y2M5MTUwZDc0IiwiaWF0IjoxNzY1MTQ5Njc0LCJleHAiOjE3NjUxNTMyNzR9.hEhyptctfEmeoYQiICNUKQehvHch24J4W9ZsAZot9BI